//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveFileInjectorRemake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveFileInjectorRemake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;playerUId&quot;:&quot;NONE&quot;,&quot;selectedCamperIndex&quot;:3,&quot;selectedSlasherIndex&quot;:268435456,&quot;firstTimePlaying&quot;:false,&quot;currentSeasonTicks&quot;:0,&quot;disconnectPenaltyTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastMatchStartTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastKillerMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastSurvivorMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;ongoingGameTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;cumulativeSessions&quot;:1,&quot;cumulativePlaytime&quot;:&quot;0&quot;,&quot;characterData&quot;:[{&quot;key&quot;:268435458,&quot;data&quot;:{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFFLINE_SAVEFILE {
            get {
                return ResourceManager.GetString("OFFLINE_SAVEFILE", resourceCulture);
            }
        }
    }
}
